# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35b99aeb6bf789d911701fb66ce11d8b9f179dd1a97b293a00904705f19d1693df6f47701e4ee5b10f4da5904ec3d091540ae9a32dd7e685573e8dadf976bc36

test:
  secret_key_base: 1b2b7daec4cace4a4ba12134db1b4f508322348ba7ba690bd585ff2aeca70fcde6ad6625680fcec0ba41e8338e913b1b082961f5120b2d01555ed6fda91d86aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
